### PR TITLE
Attempt to use catkin instead of pip3 for setup

### PR DESCRIPTION
**Pull request by linas**
Try to use the native ros catkin build tool ...

### CODE REVIEW

**Comment by linas** [comment]
Gabrieliau Can you look this over?  I thought it would be a straightforward task to just get catkin to do the setup, instead of requiring pip3. However, what's in this branch doesn't quite work: its as if "entry_points" is being ignored and I just cannot figure out why.

**Comment by Gaboose** [comment]
This says entry_points will only work correctly in installspace and not develspace. http://docs.ros.org/api/catkin/html/user_guide/setup_dot_py.html
We have to call 'catkin_make install' instead of just 'catkin_make'. And then source the install/setup.sh instead of devel/setup.bash. http://wiki.ros.org/catkin/Tutorials/using_a_workspace

**Comment by linas** [comment]
Hmm, All the tutorials say "use catkin build" (with space, no underscore).  I just tried catkin_make, it is much more verbose, and then it trashes the build so that catkin build doesn't work any more. I'm thinking that catkin_make might be an older, deprecated version ?  google does not make this clear.

**Comment by Gaboose** [comment]
Or a ros specific version. It's all catkin_make with the underscore in ros
tutorials that I can see.

**Comment by linas** [comment]
?? It says catkin build where I look. There isn't even a target called make, when you say 'catkin -h`

dpkg -S /usr/bin/catkin
python3-catkin-tools: /usr/bin/catkin

dpkg -S /opt/ros/indigo/bin/catkin_make
ros-indigo-catkin: /opt/ros/indigo/bin/catkin_make

Go figure

**Pull request closed without merging**
